# Podstawy Pythona, NumPy i Pandas

## Podstawy Pythona

Python to wszechstronny język programowania, który jest szeroko stosowany w analizie danych i uczeniu maszynowym. Oferuje prostą składnię oraz bogaty ekosystem bibliotek.

### Importowanie bibliotek

Aby korzystać z dodatkowych funkcjonalności, w Pythonie importujemy biblioteki. W kontekście analizy danych najczęściej używane są NumPy i Pandas.

In [301]:
import numpy as np
import pandas as pd

### Podstawowe typy danych
Python obsługuje kilka podstawowych typów danych:

* int: Liczby całkowite (np. ````10````).
* float: Liczby zmiennoprzecinkowe (np. ````10.5````).
* str: Napisy (np. ````'Hello'````).
* bool: Wartości logiczne (````True```` lub ````False````).
* list: Lista, która jest zbiorem uporządkowanych elementów (np. ````[1, 2, 3]````).
* tuple: Krotka, która jest zbiorem uporządkowanych, niemodyfikowalnych elementów (np. ````(1, 2, 3)````).
* dict: Słownik, który przechowuje pary klucz-wartość (np. ````{'a': 1}````).

In [302]:
# Typy danych w Pythonie
a = 10              # int
b = 10.5            # float
c = 'Hello'         # str
d = True            # bool
e = [1, 2, 3]       # list
f = (1, 2, 3)       # tuple
g = { 'a': 1, 'b': [1, 2, 3], "c": "Hello"}      # dict


In [303]:
a

10

In [304]:
b

10.5

In [305]:
c

'Hello'

In [306]:
d

True

In [307]:
e

[1, 2, 3]

In [308]:
f

(1, 2, 3)

In [309]:
g

{'a': 1, 'b': [1, 2, 3], 'c': 'Hello'}

In [310]:
d == 1

True

In [311]:
d == 0

False

In [312]:
e == f

False

In [313]:
e == [3, 2, 1]

False

In [314]:
f == (3, 2, 1)

False

In [315]:
c[0]

'H'

In [316]:
c[:-1]

'Hell'

In [317]:
e[2]

3

In [318]:
h = [[1, 2, 3], [4, 5, 6]]
h

[[1, 2, 3], [4, 5, 6]]

In [319]:
h[1]

[4, 5, 6]

In [320]:
h[1][2]

6

### Operacje na listach

Listy w Pythonie są bardzo elastyczne i oferują wiele przydatnych metod.

Oto lista najważniejszych operacji na listach w Pythonie:

1. **Tworzenie listy:**
   - Tworzenie listy za pomocą nawiasów kwadratowych `[]`, opcjonalnie z elementami początkowymi.

2. **Dostęp do elementów:**
   - Uzyskiwanie elementu listy za pomocą indeksów (od zera).
   - Używanie ujemnych indeksów do dostępu od końca listy.

3. **Modyfikacja elementów:**
   - Przypisanie nowej wartości do istniejącego indeksu listy.

4. **Dodawanie elementów:**
   - **`append()`**: Dodaje pojedynczy element na końcu listy.
   - **`extend()`**: Dodaje wiele elementów (innej listy lub iterowalnego obiektu) na końcu listy.
   - **`insert()`**: Wstawia element na określonej pozycji (indeksie).

5. **Usuwanie elementów:**
   - **`remove()`**: Usuwa pierwszy napotkany element o podanej wartości.
   - **`pop()`**: Usuwa i zwraca element na podanym indeksie (lub ostatni, jeśli nie podano indeksu).
   - **`clear()`**: Usuwa wszystkie elementy z listy.

6. **Sprawdzanie obecności elementu:**
   - **`in`**: Sprawdza, czy dany element znajduje się w liście.

7. **Długość listy:**
   - **`len()`**: Zwraca liczbę elementów w liście.

8. **Slicing (wycinanie fragmentów):**
   - Pobieranie fragmentu listy za pomocą operatora `:` (od początku, do końca, lub od jednego indeksu do innego).

9. **Sortowanie:**
   - **`sort()`**: Sortuje listę w miejscu (mutuje oryginalną listę).
   - **`sorted()`**: Zwraca nową, posortowaną wersję listy, nie zmieniając oryginału.
   - **`reverse()`**: Odwraca kolejność elementów w liście.

10. **Kopiowanie listy:**
    - **`copy()`**: Tworzy płytką kopię listy.

11. **Iterowanie po liście:**
    - Można iterować po elementach listy za pomocą pętli (np. `for`).

12. **Zagnieżdżone listy:**
    - Listy mogą zawierać inne listy, tworząc struktury wielowymiarowe.

In [321]:
my_list = [1, 2, 3]
my_list.append(4)  # Dodaje 4 do listy
print(my_list[0])  # Dostęp do pierwszego elementu (1)
my_list

1


[1, 2, 3, 4]

In [322]:
my_list.extend([5, 6, 7, 8])
my_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [323]:
my_list.remove(5)
my_list

[1, 2, 3, 4, 6, 7, 8]

In [324]:
my_list.insert(4,5)
my_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [325]:
len(my_list)

8

### Pętle i instrukcje warunkowe
W Pythonie można korzystać z pętli for oraz while, a także z instrukcji warunkowych if.

#### Pętle:

1. **`for`**:
   - Iteruje po elementach iterowalnego obiektu (takiego jak lista, krotka, słownik, czy string).
   - Powtarza blok kodu dla każdego elementu w sekwencji.

2. **`while`**:
   - Powtarza blok kodu, dopóki warunek logiczny jest spełniony (True).
   - Może powodować nieskończoną pętlę, jeśli warunek nigdy nie stanie się False.

3. **`break`**:
   - Natychmiast przerywa wykonywanie pętli, bez względu na to, czy warunek pętli (dla `while`) jest wciąż spełniony lub czy elementy do iteracji wciąż istnieją (dla `for`).

4. **`continue`**:
   - Pomija pozostałe instrukcje w aktualnej iteracji i przechodzi do następnej iteracji pętli.

5. **`else` w pętli**:
   - Blok `else` wykonywany jest po zakończeniu pętli, o ile nie zakończono jej instrukcją `break`.

6. **`pass`**:
   - Zastępuje blok kodu, który musi być składniowo poprawny, ale jeszcze nie jest zaimplementowany. Jest to "pusta" instrukcja, która nie robi nic.

In [326]:
for i in range(5):
    print(i)

0
1
2
3
4


In [327]:
for i in range(3,5):
    print(i)

3
4


In [328]:
for i in range(3,10,2):
    print(i)

3
5
7
9


In [329]:
for i in my_list:
    print(i)

1
2
3
4
5
6
7
8


In [330]:
for i in f:
    print(i)

1
2
3


In [331]:
for key, value in g.items():
    print(f"Klucz: {key}\nWartość: {value}")

Klucz: a
Wartość: 1
Klucz: b
Wartość: [1, 2, 3]
Klucz: c
Wartość: Hello


#### Instrukcje warunkowe:

1. **`if`**:
   - Sprawdza warunek logiczny; jeśli warunek jest True, wykonuje się blok kodu.

2. **`elif`**:
   - Sprawdza dodatkowy warunek, jeśli poprzedni warunek w `if` lub wcześniejszym `elif` był False. Może być używany wielokrotnie.

3. **`else`**:
   - Wykonuje blok kodu, jeśli wszystkie poprzednie warunki w `if` i `elif` były False. Jest to "domyślna" akcja na wypadek, gdy żaden warunek nie jest spełniony.

4. **Zagnieżdżone warunki**:
   - Instrukcje warunkowe mogą być zagnieżdżane, czyli jedna instrukcja `if`, `elif`, lub `else` może być wewnątrz innej instrukcji `if` lub pętli, pozwalając na bardziej złożone warunki.

5. **`ternary operator` (skrócona forma `if`):**
   - Skrócona składnia `if`, która zwraca wartość w zależności od tego, czy warunek jest True, czy False.
   - Używa składni: `wartość_jeśli_true if warunek else wartość_jeśli_false`.


In [332]:
a = 16.0
b = 16

if a > b:
    print('a jest większe niż b')
elif a == b:
    print('a jest równe b')
else:
    print('b jest większe niż a')

a jest równe b


In [333]:
print("a jest większe lub równe b") if a >= b else print("b jest większe a")

a jest większe lub równe b


### Warto pamiętać

W python istnieje też wiele operatorów, które uławtaiją nam prace z danymi numerycznymi (i nie tylko) jak chociażby operator potęgi czy dzielenia całkowitego lub reszty z dzielenia (modulo).

In [334]:
a**2

256.0

In [335]:
a/3

5.333333333333333

In [336]:
a%3

1.0

In [337]:
a//3

5.0

In [338]:
a != b

False

### Inkrementacja i dekrementacja

In [339]:
c = 0.0
while(c < a):
    print(c)
    c+=1

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0


In [340]:
c = 5
print(c)
c-=1
print(c)

5
4


### Łączenie list

Listy w python można dowolnie łączyć ze sobą.

In [341]:
for x in list(range(5,0,-1)) + list(range(1,6)):
    print("*" * x, " " * ((5-x)*2), "*" * x, sep= "")

**********
****  ****
***    ***
**      **
*        *
*        *
**      **
***    ***
****  ****
**********


### Funkcje:

1. **Definiowanie funkcji**:
   - Funkcje w Pythonie definiuje się za pomocą słowa kluczowego **`def`**. Po nim następuje nazwa funkcji oraz lista argumentów w nawiasach.
   - Blok kodu wewnątrz funkcji jest wcięty.

2. **Argumenty pozycyjne**:
   - Są to argumenty, które należy podać w odpowiedniej kolejności podczas wywoływania funkcji. Liczba podanych argumentów musi zgadzać się z liczbą argumentów w definicji funkcji.

3. **Argumenty domyślne**:
   - Można ustawić wartości domyślne dla argumentów. Jeśli argument nie zostanie podany podczas wywołania funkcji, zostanie użyta wartość domyślna.

4. **Argumenty nazwane**:
   - Podczas wywoływania funkcji można użyć nazw argumentów, co pozwala na przekazywanie argumentów w dowolnej kolejności.

5. **Zwracanie wartości**:
   - Funkcja może zwracać wynik za pomocą słowa kluczowego **`return`**. Może zwracać jedną lub więcej wartości. Jeśli nie użyjemy `return`, funkcja domyślnie zwraca `None`.

6. **Zmienne lokalne**:
   - Zmienne definiowane wewnątrz funkcji są lokalne, co oznacza, że są dostępne tylko wewnątrz tej funkcji i nie wpływają na zmienne globalne o tej samej nazwie.

7. **Zmienne globalne**:
   - Aby użyć zmiennej globalnej (zdefiniowanej poza funkcją) wewnątrz funkcji, należy zadeklarować ją jako globalną za pomocą słowa kluczowego **`global`**.

8. **Funkcje z argumentami o zmiennej długości**:
   - **`*args`**: Pozwala na przekazanie dowolnej liczby argumentów pozycyjnych jako krotki.
   - **`**kwargs`**: Pozwala na przekazanie dowolnej liczby argumentów nazwanych jako słownik.

9. **Rekurencja**:
   - Funkcja może wywoływać samą siebie. Jest to przydatne do rozwiązywania problemów, które można rozłożyć na mniejsze, takie same problemy (np. obliczanie silni).

10. **Funkcje anonimowe (lambda)**:
    - **`lambda`**: Jest to funkcja anonimowa (jednolinijkowa), która nie wymaga użycia `def`. Używana głównie dla prostych operacji, gdzie funkcja jest potrzebna jednorazowo.

11. **Zasięg zmiennych w funkcjach (LEGB rule)**:
    - Python stosuje zasadę LEGB, czyli:
      - **L (Local)** – lokalny zasięg wewnątrz bieżącej funkcji.
      - **E (Enclosing)** – zasięg zamknięcia (funkcje wewnątrz innych funkcji).
      - **G (Global)** – zasięg globalny (na poziomie modułu).
      - **B (Built-in)** – wbudowane zasięgi Pythona (np. funkcje `print()` czy `len()`).

12. **Dekoratory**:
    - Są to specjalne funkcje, które modyfikują zachowanie innych funkcji. Używa się ich, by dodać lub zmienić funkcjonalność funkcji bez zmiany jej definicji. Dekoratory oznaczamy znakiem `@` nad definicją funkcji.

13. **Funkcje jako obiekty pierwszej klasy**:
    - Funkcje w Pythonie są traktowane jako obiekty pierwszej klasy, co oznacza, że można je przypisywać do zmiennych, przekazywać jako argumenty do innych funkcji, a także zwracać z funkcji.

14. **Funkcje wbudowane**:
    - Python ma wiele funkcji wbudowanych, takich jak `len()`, `max()`, `min()`, `sum()`, które są dostępne bez konieczności ich definiowania.

In [342]:
def do_a_flip():
    return "Flip :)"

do_a_flip()

'Flip :)'

In [343]:
def dodawanie(a,b):
    return a + b

dodawanie(1, 5)

6

In [344]:
def silnia(n):
    if n in [0, 1]:
        return 1
    else:
        return n * silnia(n-1)
    
silnia(5)

120

### Klasy i obiekty:

1. **Definiowanie klasy**:
   - Klasy w Pythonie definiuje się za pomocą słowa kluczowego **`class`**, po którym następuje nazwa klasy.
   - Klasa jest szablonem do tworzenia obiektów, które są instancjami klasy.

2. **Konstruktor klasy (`__init__`)**:
   - Specjalna metoda, która jest wywoływana automatycznie przy tworzeniu nowego obiektu (instancji klasy). Używa się jej do inicjalizowania atrybutów obiektu.
   - **`self`** to pierwszy argument każdej metody w klasie, który odnosi się do instancji klasy. Używa się go do dostępu do atrybutów i metod w obrębie obiektu.

3. **Atrybuty klasy**:
   - Zmienne definiowane wewnątrz klasy, które opisują właściwości obiektu. Mogą być:
     - **Atrybutami instancji**: Każda instancja (obiekt) ma swoje własne wartości tych atrybutów.
     - **Atrybutami klasy**: Wartości współdzielone przez wszystkie instancje danej klasy.

4. **Metody**:
   - Funkcje zdefiniowane wewnątrz klasy, które działają na obiektach tej klasy.
   - **Metody instancji**: Metody, które operują na instancji klasy i używają `self`.
   - **Metody klasy (`@classmethod`)**: Metody, które operują na samej klasie, a nie na konkretnych instancjach. Pierwszym argumentem jest `cls`, który odnosi się do klasy.
   - **Metody statyczne (`@staticmethod`)**: Metody, które nie mają dostępu ani do instancji, ani do klasy. Nie używają ani `self`, ani `cls`. Są podobne do zwykłych funkcji, ale są definiowane w klasie dla logicznej organizacji.

5. **Dziedziczenie**:
   - Klasy mogą dziedziczyć właściwości i metody po innych klasach, co umożliwia tworzenie hierarchii klas.
   - Klasa dziedzicząca (podklasa) może korzystać z funkcji i atrybutów klasy bazowej (superklasy), a także może je nadpisywać lub rozszerzać.
   - **`super()`**: Używane do odwołania się do klasy nadrzędnej, umożliwiając wywołanie jej metod i konstruktorów w podklasie.

6. **Kapsułkowanie**:
   - Kapsułkowanie polega na ukrywaniu wewnętrznych szczegółów implementacji klasy przed użytkownikiem. Atrybuty i metody można oznaczać jako prywatne, poprzedzając ich nazwę podkreślnikiem `_` (wskazówka, że nie powinny być bezpośrednio modyfikowane) lub podwójnym podkreślnikiem `__` (mangle'owanie nazw, aby zmniejszyć ryzyko przypadkowej modyfikacji).

7. **Polimorfizm**:
   - Różne klasy mogą mieć metody o tej samej nazwie, ale implementować je na różne sposoby. Dzięki polimorfizmowi można wywoływać te same metody na różnych obiektach, uzyskując różne zachowania.

8. **Metody specjalne (tzw. magiczne, dunder methods)**:
   - Metody z podwójnymi podkreślnikami (`__metoda__`), które pozwalają na przeciążanie wbudowanych operacji, takich jak tworzenie reprezentacji obiektu, porównywanie, czy operacje matematyczne.
   - **`__str__`** i **`__repr__`**: Definiują, jak obiekt będzie reprezentowany jako string.
   - **`__len__`**: Zwraca długość obiektu (używane np. w `len()`).
   - **`__eq__`**: Służy do porównywania obiektów (operacja `==`).
   - **`__add__`**: Definiuje działanie operatora `+` dla obiektów.
   
9. **Abstrakcja**:
   - Klasy mogą zawierać metody abstrakcyjne, które muszą zostać zaimplementowane przez klasy dziedziczące.
   - Używa się tego w przypadku klas bazowych, które pełnią funkcję szablonów, ale same nie mają pełnej funkcjonalności.
   - Moduł `abc` w Pythonie pozwala na definiowanie klas i metod abstrakcyjnych za pomocą dekoratora **`@abstractmethod`**.

10. **Hermetyzacja (encapsulation)**:
    - Hermetyzacja polega na ograniczaniu dostępu do wewnętrznych elementów klasy. W Pythonie nie ma ścisłego mechanizmu hermetyzacji (jak np. `private` w innych językach), ale można stosować konwencje nazw (podkreślenie `__` przed nazwą atrybutu), by zasugerować, że dany atrybut lub metoda nie powinny być dostępne spoza klasy.

11. **Kompozycja**:
    - Klasy mogą zawierać inne klasy jako atrybuty, co pozwala na budowanie bardziej złożonych struktur poprzez łączenie mniejszych obiektów. To alternatywa dla dziedziczenia, umożliwiająca elastyczniejsze budowanie zależności między obiektami.

12. **Wyjątki i obsługa błędów w klasach**:
    - Klasy mogą definiować własne wyjątki, dziedzicząc po wbudowanej klasie **`Exception`**. Pozwala to na tworzenie specyficznych wyjątków związanych z danym typem obiektów lub kontekstem aplikacji.

In [345]:
class Osoba:
    imie: str
    nazwisko: str
    wiek: int
    
    def __init__(self, imie: str, nazwisko: str, wiek: int):
        self.imie = imie
        self.nazwisko = nazwisko
        self.wiek = wiek

    def przedstaw_sie(self):
        print('Nazywam się {0} {1}'.format(self.imie, self.nazwisko))

    def moj_wiek(self):
        print('Mój wiek to: {0}.'.format(self.wiek))
        
    def __repr__(self) -> str:
        return self.przedstaw_sie() + "\n" + self.moj_wiek()
    
    def __str__(self) -> str:
        return self.przedstaw_sie() + "\n" + self.moj_wiek()


os = Osoba('Jan', 'Kowalski', 13)
os.przedstaw_sie()
os.moj_wiek()

Nazywam się Jan Kowalski
Mój wiek to: 13.


### Python Comprehension:

1. **List Comprehension (tworzenie list)**:
   - Umożliwia tworzenie nowych list w bardziej zwięzły i czytelny sposób.
   - Syntaktycznie prostsza alternatywa dla pętli, która umożliwia generowanie list na podstawie istniejących sekwencji.
   - Składnia: `[expression for item in iterable]`.

2. **Dict Comprehension (tworzenie słowników)**:
   - Umożliwia tworzenie słowników w podobny sposób jak list comprehension, ale generuje pary klucz-wartość.
   - Składnia: `{key_expression: value_expression for item in iterable}`.

3. **Set Comprehension (tworzenie zbiorów)**:
   - Umożliwia tworzenie zbiorów za pomocą jednej linii kodu. Podobne do list comprehension, ale wynikiem jest zbiór.
   - Składnia: `{expression for item in iterable}`.

4. **Generator Comprehension (tworzenie generatorów)**:
   - Generatory działają podobnie jak list comprehension, ale zamiast tworzyć od razu pełną listę, zwracają generator, który generuje elementy „na żądanie”, co oszczędza pamięć.
   - Składnia: `(expression for item in iterable)`.

5. **Comprehension z warunkiem (opcjonalny `if`)**:
   - Comprehension można rozszerzyć o warunek, aby filtrować elementy przed ich przetworzeniem.
   - Dla list: `[expression for item in iterable if condition]`.
   - Dla słowników: `{key_expression: value_expression for item in iterable if condition}`.

6. **Zagnieżdżone comprehension**:
   - Python pozwala na używanie zagnieżdżonych comprehension do generowania złożonych struktur danych (np. list wielowymiarowych).
   - Składnia: `[expression for item1 in iterable1 for item2 in iterable2]`.

---

### Szczegółowe opisy:

1. **List Comprehension**:
   - Jest to najczęściej używany rodzaj comprehension. Pozwala przekształcać elementy istniejącej listy lub innej iterowalnej struktury do nowej listy, zgodnie z zadaną operacją lub przekształceniem.
   - Idealne do prostych transformacji danych oraz do filtrowania danych w jednej linii.

2. **Dict Comprehension**:
   - Dict comprehension działa w podobny sposób jak list comprehension, ale zamiast listy tworzy słownik. Każdy element iteracji generuje parę klucz-wartość, która zostanie dodana do nowego słownika.
   - Służy do przekształcania istniejących danych w nowe słowniki lub do filtrowania i manipulowania słownikami.

3. **Set Comprehension**:
   - Set comprehension tworzy zbiory w sposób podobny do list comprehension, ale wynikiem jest zbiór, co oznacza, że duplikaty są automatycznie usuwane.
   - Stosuje się je, gdy zależy nam na unikalnych elementach w wynikowej strukturze.

4. **Generator Comprehension**:
   - Generatory są bardziej efektywne pamięciowo, ponieważ nie tworzą od razu pełnej listy, ale elementy są generowane dopiero, gdy są potrzebne.
   - Idealne do pracy z dużymi zestawami danych, gdzie nie chcemy ładować wszystkich elementów naraz do pamięci.

5. **Comprehension z warunkiem (`if`)**:
   - Warunek umieszczony po iteracji pozwala filtrować elementy, które spełniają określony warunek. Jest to przydatne, gdy chcemy w jednej linii zarówno filtrować, jak i przekształcać dane.
   - Można go używać we wszystkich rodzajach comprehension (list, dict, set, generator).

6. **Zagnieżdżone comprehension**:
   - Zagnieżdżone comprehension pozwala na iterację po wielu kolekcjach w jednej linii. Jest to bardziej złożona technika, ale umożliwia tworzenie wielowymiarowych struktur danych.
   - Używane z rozwagą, gdyż może znacząco obniżyć czytelność kodu.

In [346]:
x = []
for i in range(5):
    x.append(i)
x

[0, 1, 2, 3, 4]

In [347]:
x = [x for x in range(5)]
x

[0, 1, 2, 3, 4]

In [348]:
x = []
for i in range(11):
    if i % 2 == 0:
        x.append(i)
x

[0, 2, 4, 6, 8, 10]

In [349]:
x = [x for x in range(11) if x % 2 == 0]
x

[0, 2, 4, 6, 8, 10]

### Obsługa plików:

1. **Otwieranie pliku (`open()`)**:
   - Funkcja **`open()`** służy do otwierania pliku w określonym trybie (np. do odczytu, zapisu). Zwraca obiekt pliku, na którym można wykonywać dalsze operacje.
   - Możliwe tryby otwierania plików:
     - **`'r'`**: Tryb odczytu (domyślny). Plik musi istnieć, inaczej wystąpi błąd.
     - **`'w'`**: Tryb zapisu. Tworzy nowy plik lub nadpisuje istniejący.
     - **`'a'`**: Tryb dopisywania. Dodaje dane na końcu istniejącego pliku.
     - **`'x'`**: Tryb tworzenia nowego pliku. Zgłasza błąd, jeśli plik już istnieje.
     - **`'b'`**: Tryb binarny, używany do odczytu lub zapisu plików binarnych.
     - **`'t'`**: Tryb tekstowy (domyślny), używany do odczytu lub zapisu plików tekstowych.

2. **Zamykanie pliku (`close()`)**:
   - Po zakończeniu pracy z plikiem, plik należy zamknąć za pomocą metody **`close()`**, aby zwolnić zasoby systemowe. Python automatycznie zamyka plik po zakończeniu programu, ale najlepiej robić to ręcznie, aby uniknąć problemów.

3. **Kontekst menedżera (`with` as)**:
   - Użycie **`with`** zapewnia automatyczne zamknięcie pliku po zakończeniu jego używania, nawet jeśli wystąpi błąd. Jest to zalecana metoda otwierania plików.

4. **Odczyt pliku**:
   - **`read()`**: Odczytuje cały plik jako jeden ciąg znaków.
   - **`readline()`**: Odczytuje pojedynczą linię tekstu z pliku.
   - **`readlines()`**: Odczytuje wszystkie linie z pliku i zwraca je jako listę.

5. **Zapis do pliku**:
   - **`write()`**: Zapisuje dane do pliku. Jeśli plik został otwarty w trybie `'w'` lub `'a'`, nadpisuje lub dopisuje dane.
   - **`writelines()`**: Zapisuje listę danych do pliku. Każdy element listy zostaje zapisany jako osobna linia.

6. **Sprawdzanie pozycji w pliku**:
   - **`tell()`**: Zwraca bieżącą pozycję kursora w pliku (w bajtach).
   - **`seek()`**: Ustawia kursor na określoną pozycję w pliku (np. przewijanie na początek lub konkretny punkt w pliku).

7. **Tryby pracy na plikach binarnych**:
   - Pliki binarne, takie jak obrazy lub pliki audio, są otwierane z użyciem trybu `'b'`. Operacje na nich działają podobnie jak na plikach tekstowych, ale dane są odczytywane jako bajty.
   - **`rb`**: Odczyt binarny.
   - **`wb`**: Zapis binarny.

8. **Pliki tymczasowe (`tempfile`)**:
   - Moduł **`tempfile`** umożliwia tworzenie tymczasowych plików i katalogów, które są automatycznie usuwane po zakończeniu pracy programu lub po zamknięciu pliku.

9. **Obsługa wyjątków podczas pracy z plikami**:
   - Podczas pracy z plikami mogą wystąpić różne wyjątki, takie jak **`FileNotFoundError`**, jeśli plik nie istnieje, lub **`IOError`**, jeśli występuje problem z operacjami wejścia/wyjścia. Obsługa wyjątków jest kluczowa, aby program był odporny na błędy.

10. **Zarządzanie dużymi plikami**:
    - Aby unikać zbyt dużego zużycia pamięci, należy odczytywać pliki fragmentami (np. linia po linii) zamiast odczytywania całego pliku naraz.

In [350]:
plik = open('test.txt')
dane = plik.read()
print(dane)
plik.close()

1 2 3 4
5 6 6 7
9 10 11 12
ą ę ć ż


In [351]:
plik = open('test.txt', encoding='utf-8')
dane = plik.read()
print(dane)
plik.close()

1 2 3 4
5 6 6 7
9 10 11 12
ą ę ć ż


In [352]:
plik = open('test.txt', encoding='utf-8')
for linia in plik:
    print(linia)
plik.close()

1 2 3 4

5 6 6 7

9 10 11 12

ą ę ć ż


In [353]:
with open("test.txt", "r", encoding="utf-8") as plik:
    for linia in plik:
        print(linia)

1 2 3 4

5 6 6 7

9 10 11 12

ą ę ć ż


## NumPy
NumPy to jedna z najważniejszych bibliotek Pythona do obliczeń numerycznych. Umożliwia efektywne przetwarzanie dużych zbiorów danych, dzięki czemu jest często wykorzystywana w analizie danych i uczeniu maszynowym.

NumPy oferuje szeroki zestaw narzędzi do pracy z tablicami, macierzami i operacjami numerycznymi, co czyni go niezwykle efektywnym narzędziem do analizy danych oraz wykonywania operacji matematycznych na dużych zbiorach danych.

### NumPy Comprehension:

1. **Tworzenie tablic (ndarray)**:
   - NumPy oferuje funkcję **`numpy.array()`** do tworzenia wielowymiarowych tablic (ndarray). Jest to podstawowa struktura danych NumPy, pozwalająca na przechowywanie i operowanie na liczbach.
   
2. **Tworzenie tablic z wartościami zerowymi i jedynkami**:
   - **`numpy.zeros()`**: Tworzy tablicę wypełnioną zerami o zadanym kształcie.
   - **`numpy.ones()`**: Tworzy tablicę wypełnioną jedynkami o zadanym kształcie.

3. **Tworzenie tablic z wartościami losowymi**:
   - **`numpy.random.rand()`**: Tworzy tablicę o zadanym kształcie z losowymi wartościami z zakresu [0, 1) (rozkład jednostajny).
   - **`numpy.random.randn()`**: Tworzy tablicę z losowymi wartościami z rozkładu normalnego (średnia 0, odchylenie standardowe 1).

4. **Tworzenie tablic arytmetycznych**:
   - **`numpy.arange()`**: Tworzy tablicę z ciągiem liczb w danym przedziale, z opcją zdefiniowania kroku.
   - **`numpy.linspace()`**: Tworzy tablicę z liczbami równomiernie rozmieszczonymi w określonym przedziale.

5. **Podstawowe operacje arytmetyczne**:
   - NumPy pozwala na wykonywanie operacji arytmetycznych na tablicach w sposób elementarny (element-wise). Obsługiwane są operacje takie jak dodawanie, odejmowanie, mnożenie, dzielenie oraz operacje na potęgach.
   - Przykłady: **`+`, `-`, `*`, `/`, `**`** (operacje wykonywane są dla odpowiadających sobie elementów tablic).

6. **Transponowanie tablicy (`.T`)**:
   - **`ndarray.T`**: Zwraca transponowaną tablicę (zamiana wierszy na kolumny i odwrotnie).

7. **Kształtowanie i zmiana wymiarów tablicy**:
   - **`numpy.reshape()`**: Zmienia kształt tablicy, bez zmiany jej zawartości.
   - **`numpy.flatten()`**: Spłaszcza wielowymiarową tablicę do jednowymiarowej.
   - **`numpy.ravel()`**: Podobna do `flatten`, ale zwraca widok na oryginalną tablicę, a nie kopię.

8. **Indeksowanie i wycinanie (slicing)**:
   - NumPy pozwala na zaawansowane indeksowanie tablic, w tym:
     - **Indeksowanie skalarem**: Dostęp do pojedynczego elementu tablicy za pomocą jego indeksu.
     - **Wycinanie (slicing)**: Wyodrębnianie fragmentów tablicy przy użyciu operatora `:`.

9. **Operacje na osi (axis)**:
   - W NumPy można wykonywać operacje wzdłuż określonej osi tablicy.
   - **`axis=0`** odnosi się do operacji wzdłuż kolumn (w kierunku pionowym).
   - **`axis=1`** odnosi się do operacji wzdłuż wierszy (w kierunku poziomym).

10. **Agregacja danych**:
    - **`numpy.sum()`**: Zwraca sumę elementów tablicy.
    - **`numpy.mean()`**: Zwraca średnią arytmetyczną elementów tablicy.
    - **`numpy.max()`**, **`numpy.min()`**: Zwracają odpowiednio największy i najmniejszy element tablicy.
    - **`numpy.std()`**: Oblicza odchylenie standardowe elementów w tablicy.
    - **`numpy.median()`**: Oblicza medianę elementów w tablicy.

11. **Łączenie i dzielenie tablic**:
    - **`numpy.concatenate()`**: Łączy dwie lub więcej tablic wzdłuż określonej osi.
    - **`numpy.vstack()`**: Łączy tablice pionowo (wzdłuż wierszy).
    - **`numpy.hstack()`**: Łączy tablice poziomo (wzdłuż kolumn).
    - **`numpy.split()`**: Dzieli tablicę na podtablice według określonego podziału.

12. **Operacje logiczne i maski**:
    - NumPy obsługuje operacje logiczne na tablicach, takie jak porównywanie elementów, np. **`>`, `<`, `==`**, zwracając tablice wartości logicznych.
    - **Maski logiczne**: Używane do filtrowania danych. Maski pozwalają na wybieranie elementów tablicy spełniających określone warunki.

13. **Macierze i algebra liniowa**:
    - NumPy zawiera funkcje do operacji na macierzach i operacji algebraicznych.
    - **`numpy.dot()`**: Iloczyn macierzowy (mnożenie macierzy).
    - **`numpy.linalg.inv()`**: Odwracanie macierzy.
    - **`numpy.linalg.eig()`**: Obliczanie wartości i wektorów własnych macierzy.

14. **Broadcasting**:
    - Mechanizm NumPy, który automatycznie rozszerza rozmiary tablic o różnych wymiarach, aby umożliwić wykonywanie operacji arytmetycznych między nimi.
    - Pozwala na wykonywanie operacji między tablicami o różnych kształtach, bez konieczności jawnego powiększania mniejszych tablic.

15. **Obsługa brakujących wartości (`NaN`)**:
    - NumPy oferuje funkcje do pracy z brakującymi danymi:
      - **`numpy.isnan()`**: Sprawdza, które elementy tablicy są `NaN` (brak wartości).
      - **`numpy.nan_to_num()`**: Zamienia wartości `NaN` na zdefiniowane liczby.

### Tworzenie tablic NumPy
Tablice NumPy są bardziej wydajne niż tradycyjne listy Pythona.

In [354]:
np_array = np.array([1, 2, 3, 4])
np_array

array([1, 2, 3, 4])

### Podstawowe operacje na tablicach
NumPy umożliwia wykonywanie operacji na całych tablicach bez potrzeby używania pętli.

In [355]:
np_array += 1                   # Dodaje 1 do każdego 
print(np_array)
np_array *= 3                   # Mnoży każdy element przez 3
print(np_array)
np_array = np.sqrt(np_array)    # Pierwiastek kwadratowy z każdego elementu
print(np_array)

[2 3 4 5]
[ 6  9 12 15]
[2.44948974 3.         3.46410162 3.87298335]


### Indeksowanie i wycinanie
Można uzyskiwać dostęp do poszczególnych elementów tablicy, a także wycinać fragmenty.

In [356]:
print(np_array[0])          # Pierwszy element
print(np_array[1:3])        # Elementy od indeksu 1 do 2

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[1,2])            # Element z w wiersza i 3 kolumny

2.449489742783178
[3.         3.46410162]
6


### Statystyki
NumPy dostarcza funkcji do obliczeń statystycznych.

In [357]:
print(np.mean(np_array))     # Średnia
print(np.std(np_array))      # Odchylenie standardowe
print(np.sum(np_array))      # Suma wszystkich elementów

3.196643676032087
0.5305367173759638
12.786574704128348


### Operacje na macierzach
NumPy pozwala na wykonywanie operacji na macierzach, takich jak mnożenie czy transpozycja.

In [358]:
print(np.dot(arr2, arr2))       # Mnożenie macierzy
print(np.transpose(arr2))       # Transpozycja macierzy+
arr2 *= arr2
print(arr2)
print(np.linalg.det(arr2))      # Wyznacznik macierzy
print(np.diag(arr2))            # Przekątna macierzy

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
-216.00000000000006
[ 1 25 81]


In [359]:
# Tworzenie tablicy od 0 do 10 z krokiem 2
tablica_arange = np.arange(0, 10, 2)
print(tablica_arange)  # Wynik: [0 2 4 6 8]

[0 2 4 6 8]


In [360]:
# Tworzenie tablicy z 5 równymi wartościami od 0 do 1
tablica_linspace = np.linspace(0, 1, 5)
print(tablica_linspace)  # Wynik: [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


In [361]:
# Tworzenie 2x3 tablicy wypełnionej jedynkami
tablica_ones = np.ones((2, 3))
print(tablica_ones)
# Wynik:
# [[1. 1. 1.]
#  [1. 1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]]


In [362]:
# Tworzenie 2x3 tablicy wypełnionej zerami
tablica_zeros = np.zeros((2, 3))
print(tablica_zeros)
# Wynik:
# [[0. 0. 0.]
#  [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [363]:
# Tworzenie 3x3 macierzy jednostkowej
macierz_jednostkowa = np.eye(3)
print(macierz_jednostkowa)
# Wynik:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [364]:
# Tworzenie tablicy 2x3 z losowymi wartościami z rozkładu jednostajnego
tablica_random = np.random.rand(2, 3)
print(tablica_random)
# Wynik może być różny, np.:
# [[0.5488135  0.71518937 0.60276338]
#  [0.54488318 0.4236548  0.64589411]]


[[0.0072655  0.59936058 0.44407981]
 [0.45941305 0.14721138 0.82961323]]


## Pandas
Pandas to biblioteka do manipulacji i analizy danych. Oferuje dwa główne typy obiektów: Series (jednowymiarowe) i DataFrame (dwuwymiarowe), które są szczególnie przydatne do pracy z danymi tabelarycznymi.

Pandas to potężna biblioteka do analizy danych w Pythonie, która umożliwia łatwe manipulowanie danymi tabelarycznymi, zarządzanie brakującymi wartościami oraz przeprowadzanie złożonych operacji agregacyjnych i transformacyjnych. Jest szeroko stosowana w dziedzinach takich jak analiza danych, eksploracja danych oraz uczenie maszynowe.

### Pandas:

1. **Tworzenie obiektów DataFrame i Series**:
   - **`pd.DataFrame()`**: Umożliwia tworzenie tabeli danych (DataFrame), która jest podstawową strukturą danych w Pandas. Może zawierać różne typy danych (np. liczby, teksty) w kolumnach.
   - **`pd.Series()`**: Tworzy jednowymiarową tablicę danych, podobną do kolumny w DataFrame, która może mieć dowolny typ danych.

2. **Wczytywanie danych**:
   - **`pd.read_csv()`**: Wczytuje dane z pliku CSV do DataFrame. Umożliwia różne opcje konfiguracyjne (np. separator, nagłówki).
   - **`pd.read_excel()`**: Wczytuje dane z pliku Excel (XLS, XLSX) do DataFrame.
   - **`pd.read_sql()`**: Wczytuje dane z bazy danych SQL do DataFrame.

3. **Eksportowanie danych**:
   - **`DataFrame.to_csv()`**: Eksportuje dane z DataFrame do pliku CSV.
   - **`DataFrame.to_excel()`**: Eksportuje dane z DataFrame do pliku Excel.
   - **`DataFrame.to_sql()`**: Zapisuje dane z DataFrame do bazy danych SQL.

4. **Inspekcja danych**:
   - **`DataFrame.head()`**: Zwraca pierwsze n wierszy z DataFrame, co umożliwia szybki podgląd danych.
   - **`DataFrame.tail()`**: Zwraca ostatnie n wierszy z DataFrame.
   - **`DataFrame.info()`**: Wyświetla podsumowanie DataFrame, w tym liczby wierszy, kolumn oraz typy danych.
   - **`DataFrame.describe()`**: Zwraca statystyki opisowe dla danych liczbowych w DataFrame (np. średnia, mediana, min, max).

5. **Indeksowanie i wybieranie danych**:
   - **`DataFrame.loc[]`**: Umożliwia wybieranie danych na podstawie etykiet indeksów (kolumn i wierszy).
   - **`DataFrame.iloc[]`**: Umożliwia wybieranie danych na podstawie pozycji indeksów (numerycznych).
   - **`DataFrame.at[]`**: Służy do szybkiego dostępu do pojedynczych wartości przy użyciu etykiet indeksów.
   - **`DataFrame.iat[]`**: Służy do szybkiego dostępu do pojedynczych wartości przy użyciu pozycji indeksów.

6. **Filtracja i wycinanie**:
   - Umożliwia filtrowanie danych na podstawie warunków (np. **`DataFrame[DataFrame['kolumna'] > wartość]`**).
   - Możliwość tworzenia nowych DataFrame z wybranymi kolumnami lub wierszami.

7. **Modyfikacja danych**:
   - **`DataFrame['kolumna'] = value`**: Możliwość przypisania nowych wartości do kolumny w DataFrame.
   - **`DataFrame.drop()`**: Usuwa kolumny lub wiersze z DataFrame.
   - **`DataFrame.rename()`**: Zmienia nazwy kolumn lub indeksów w DataFrame.

8. **Agregacja i grupowanie**:
   - **`DataFrame.groupby()`**: Umożliwia grupowanie danych na podstawie określonych kolumn i wykonywanie operacji agregacyjnych (np. sumy, średnie).
   - **`DataFrame.agg()`**: Umożliwia stosowanie różnych funkcji agregacyjnych do grupowanych danych.

9. **Sortowanie danych**:
   - **`DataFrame.sort_values()`**: Sortuje wiersze w DataFrame według wartości w określonej kolumnie.
   - **`DataFrame.sort_index()`**: Sortuje wiersze w DataFrame według indeksu.

10. **Operacje na brakujących danych**:
    - **`DataFrame.isnull()`**: Sprawdza, które wartości są brakujące (NaN) w DataFrame.
    - **`DataFrame.fillna()`**: Umożliwia wypełnienie brakujących wartości określoną wartością lub metodą.
    - **`DataFrame.dropna()`**: Usuwa wiersze lub kolumny z brakującymi wartościami.

11. **Łączenie danych**:
    - **`pd.concat()`**: Łączy różne DataFrame wzdłuż określonej osi (wiersze lub kolumny).
    - **`pd.merge()`**: Łączy dwa DataFrame na podstawie wspólnych kolumn (operacja podobna do SQL JOIN).

12. **Zapis do plików**:
    - **`DataFrame.to_csv()`**: Zapisuje dane z DataFrame do pliku CSV.
    - **`DataFrame.to_excel()`**: Zapisuje dane z DataFrame do pliku Excel.

13. **Operacje czasowe**:
    - Pandas ma rozbudowane wsparcie dla operacji na danych czasowych.
    - **`pd.to_datetime()`**: Konwertuje obiekty na format daty/czasu.
    - **`DataFrame.resample()`**: Umożliwia agregowanie danych czasowych w określonych interwałach (np. dzienne, miesięczne).

14. **Zastosowanie funkcji**:
    - **`DataFrame.apply()`**: Umożliwia stosowanie funkcji do wierszy lub kolumn w DataFrame.
    - **`DataFrame.map()`**: Stosuje funkcję do elementów w danej kolumnie.

15. **Wizualizacja danych**:
    - Pandas współpracuje z biblioteką Matplotlib, umożliwiając prostą wizualizację danych z DataFrame.
    - **`DataFrame.plot()`**: Umożliwia tworzenie wykresów na podstawie danych w DataFrame.

### Tworzenie DataFrame
DataFrame jest kluczowym obiektem w Pandas, który reprezentuje dane w postaci tabeli.

In [365]:
data = {
    'Kolumna1': [1, 2, 3],
    'Kolumna2': [4, 5, 6]
}
df = pd.DataFrame(data)
print(df)

   Kolumna1  Kolumna2
0         1         4
1         2         5
2         3         6


### Wczytywanie danych z pliku
Pandas umożliwia łatwe wczytywanie danych z plików.

In [366]:
df = pd.read_csv('test.txt', header= None, delimiter= " ")
df

0   1   2   3
0  1   2   3   4
1  5   6   6   7
2  9  10  11  12
3  ą   ę   ć   ż

### Podstawowe operacje na DataFrame
Pandas oferuje wiele przydatnych metod do analizy danych.

In [367]:
df.head(2)             # Pierwsze 2 wierszy (domyślnie 5)


0  1  2  3
0  1  2  3  4
1  5  6  6  7

In [368]:
df.describe()         # Statystyki opisowe

0  1  2  3
count   4  4  4  4
unique  4  4  4  4
top     1  2  3  4
freq    1  1  1  1

In [369]:
df.info()             # Informacje o DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       4 non-null      object
 1   1       4 non-null      object
 2   2       4 non-null      object
 3   3       4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes


### Indeksowanie i wycinanie danych
Można uzyskiwać dostęp do kolumn i wierszy w DataFrame.

In [370]:
df.columns = ["k1" , "k2", "k3", "k4"]

In [371]:
df['k1']                # Dostęp do kolumny

0    1
1    5
2    9
3    ą
Name: k1, dtype: object

In [372]:
df.loc[0]               # Dostęp do pierwszego wiersza

k1    1
k2    2
k3    3
k4    4
Name: 0, dtype: object

In [373]:
df.iloc[0:2]             # Wiersze od 0 do 1

k1 k2 k3 k4
0  1  2  3  4
1  5  6  6  7

### Dodawanie i usuwanie kolumn
Można dodawać nowe kolumny do DataFrame oraz usuwać istniejące.

In [374]:
df['k5'] = df['k1'] + df['k2']              # Dodanie nowej kolumny
df

k1  k2  k3  k4   k5
0  1   2   3   4   12
1  5   6   6   7   56
2  9  10  11  12  910
3  ą   ę   ć   ż   ąę

In [375]:
df.drop('k3', axis= 1, inplace=True)         # Usunięcie kolumny
df

k1  k2  k4   k5
0  1   2   4   12
1  5   6   7   56
2  9  10  12  910
3  ą   ę   ż   ąę

In [376]:
df.drop(3, axis= 0, inplace= True)          # Usunięcie wiersza
df

k1  k2  k4   k5
0  1   2   4   12
1  5   6   7   56
2  9  10  12  910

In [377]:
df.dtypes

k1    object
k2    object
k4    object
k5    object
dtype: object

In [378]:
for i in [1,2,4,5]:
    df[f"k{i}"] = df[f"k{i}"].astype(int)
df.dtypes

k1    int32
k2    int32
k4    int32
k5    int32
dtype: object

In [379]:
df

k1  k2  k4   k5
0   1   2   4   12
1   5   6   7   56
2   9  10  12  910

In [380]:
df['k6'] = df['k1'] + df['k2']              # Dodanie nowej kolumny
df

k1  k2  k4   k5  k6
0   1   2   4   12   3
1   5   6   7   56  11
2   9  10  12  910  19

### Grupowanie danych
Pandas umożliwia grupowanie danych i wykonywanie na nich operacji agregacyjnych.

In [381]:
# Tworzenie przykładowego DataFrame
data = {
    'Produkt': ['A', 'B', 'A', 'B', 'A', 'C', 'B', 'C'],
    'Kategoria': ['X', 'X', 'Y', 'Y', 'X', 'Y', 'X', 'Y'],
    'Sprzedaż': [100, 150, 200, 300, 250, 100, 350, 400]
}

df = pd.DataFrame(data)
df

Produkt Kategoria  Sprzedaż
0       A         X       100
1       B         X       150
2       A         Y       200
3       B         Y       300
4       A         X       250
5       C         Y       100
6       B         X       350
7       C         Y       400

In [382]:
# Grupowanie według Kategorii i sumowanie Sprzedaży
grupowane_df = df.groupby('Kategoria')['Sprzedaż'].sum().reset_index()

print("\nZgrupowane i zsumowane dane:")
print(grupowane_df)


Zgrupowane i zsumowane dane:
  Kategoria  Sprzedaż
0         X       850
1         Y      1000


### Zapisywanie DataFrame do pliku CSV
Pandas pozwala na łatwe zapisywanie danych do plików CSV.

In [383]:
df.to_csv('wyniki.csv', sep= " ", index=False)  # Zapis do pliku CSV

# **Zadania**

(Te zadania nie są oceniane - Napisz dla własnej praktyki :) )
1. Napisz funkcję, która przyjmuje listę i zwraca nową listę z unikalnymi elementami tej listy (bez powtórzeń).
2. Napisz funkcję, która łączy dwie listy w jedną, usuwając duplikaty.
3. Napisz funkcję, która znajduje wszystkie liczby pierwsze w zadanym zakresie (np. od 1 do 100).
4. Napisz funkcję rekurencyjną, która zwraca n-ty wyraz ciągu Fibonacciego.
5. Stwórz klasę Prostokat, która ma atrybuty dlugosc i szerokosc, oraz metody obliczające pole i obwód. Dodaj jeszzcze jedną metodę według uznania.
6. Użyj list comprehension, aby stworzyć listę kwadratów liczb od 1 do 20.
7. Napisz funkcję, która zapisuje listę liczb do pliku tekstowego.
8. Napisz funkcję, która odczytuje liczby z pliku tekstowego i zwraca je jako listę.

(Te zadania będą oceniane - Te musisz napisać :) )


9. Stwórz tablicę NumPy i pomnóż ją przez wektor.
10. Stwórz sub-tablicę z większej tablicy NumPy (np. 2x2 sub-tablica z 4x4 tablicy).
11. Wygeneruj macierz losową o wymiarach 5x5, a następnie znajdź jej macierz odwrotną. Sprawdź, czy iloczyn macierzy i jej odwrotności daje macierz jednostkową.
12. Utwórz dwie macierze 3x3 z losowymi wartościami i oblicz ich iloczyn macierzowy. Następnie dodaj do wyniku macierz jednostkową.
13. Utwórz tablicę 2D z losowymi wartościami i oblicz średnią, medianę oraz odchylenie standardowe dla każdej kolumny.
14. Wczytaj dane z pliku CSV zawierającego informacje o sprzedaży (np. plik sales_data.csv). Zastosuj metody head(), info(), describe() do analizy danych.
15. Wykorzystaj dane o sprzedaży do grupowania według kategorii produktów. Oblicz łączną sprzedaż dla każdej kategorii oraz średnią cenę produktu.
16. Filtruj dane o sprzedaży, aby znaleźć wszystkie transakcje, które miały miejsce w 2013 roku i miały wartość większą niż 3500. Wyświetl wyniki.
17. Zmień nazwę kolumny "Product" na "Product_Name" w DataFrame. Użyj list comprehension.
18. Dodaj nową kolumnę "Rabat", która będzie zawierać rabaty w wysokości 10% od wartości transakcji.
19. Po wykonaniu wszystkich operacji na danych o sprzedaży, zapisz przetworzony DataFrame do nowego pliku CSV o nazwie processed_sales_data.csv.
20. Użyj metody plot() do stworzenia wykresu słupkowego, który przedstawia łączną liczbę sprzedaży dla różnych kategorii produktów.